### PR TITLE
Issue 21

### LINKED ISSUE #21: Unable to associate parameter name with single non-annotated constructor argument
With Jackson 2.6.0-rc2 and the parameter names module, I am running into errors when deserializing JSON into objects with one constructor argument.  Here is some sample code demonstrating the issue:

```
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;

import java.io.IOException;
import java.util.List;

public class Example {
  static class NoAnnotations {
    NoAnnotations(List<Integer> numbers) {
      System.out.println(numbers);
    }
  }

  static class CreatorOnly {
    @JsonCreator
    CreatorOnly(List<Integer> numbers) {
      System.out.println(numbers);
    }
  }

  static class CreatorAndProperty {
    @JsonCreator
    CreatorAndProperty(@JsonProperty("numbers") List<Integer> numbers) {
      System.out.println(numbers);
    }
  }

  static class PropertyOnly {
    PropertyOnly(@JsonProperty("numbers") List<Integer> numbers) {
      System.out.println(numbers);
    }
  }

  static class SecondArgument {
    SecondArgument(List<Integer> numbers, List<Integer> moreNumbers) {
      System.out.println(numbers);
    }
  }

  public static void main(String[] args) {
    String json = "{\"numbers\":[1,2,3]}";
    ObjectMapper mapper = new ObjectMapper()
        .registerModule(new ParameterNamesModule());
    try {
      // This throws.
      mapper.readValue(json, NoAnnotations.class);
    } catch (IOException e) {
      e.printStackTrace();
    }
    try {
      // This throws.
      mapper.readValue(json, CreatorOnly.class);
    } catch (IOException e) {
      e.printStackTrace();
    }
    try {
      // This is ok.
      mapper.readValue(json, CreatorAndProperty.class);
    } catch (IOException e) {
      e.printStackTrace();
    }
    try {
      // This is ok.
      mapper.readValue(json, PropertyOnly.class);
    } catch (IOException e) {
      e.printStackTrace();
    }
    try {
      // This is ok.
      mapper.readValue(json, SecondArgument.class);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
```

Here is the output of the above.

```
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class Example$None]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"numbers":[1,2,3]}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3707)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2719)
	at Example.main(Example.java:47) <5 internal calls>
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of FIELD_NAME token
 at [Source: {"numbers":[1,2,3]}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:850)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:846)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1096)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3707)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2719)
	at Example.main(Example.java:52) <5 internal calls>
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
```

My real code most closely resembles the `NoAnnotations` example.  Is it a bug that that example throws, or is that an expected limitation?

### PR DESCRIPTION
**Pull request by lpandzic**
Fixes #21

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Would this work for case where there are multiple constructors?

**Comment by cowtowncoder** [comment]
Ok. Looking at core jackson-databind, issue in not finding implicitly named creator parameters, I think that while I do want to fix that, timing is such that fix won't make it in 2.6. Given this, I think approach here makes sense in general.

However, I do want to be sure that this would work even in presence of multiple creators (so there are no bogus conflicts). And also setting should not override explicit `@JsonCreator.mode`.
It may also make sense to have a true/false option to simply force use of `PROPERTIES`?

**Comment by lpandzic** [comment]
I don't know if you've noteiced, but the code in PR is backwards compatible and does not assume property JsonCreator mode.

> However, I do want to be sure that this would work even in presence of multiple creators (so there are no bogus conflicts).

You mean multiple constructors?

> And also setting should not override explicit @JsonCreator.mode.

I agree, does core handle this?

> It may also make sense to have a true/false option to simply force use of PROPERTIES?

Are you suggesting to change JsonCreator.mode parameter of the module constructor with a boolean flag?

**Comment by cowtowncoder** [comment]
Right, I understand that it is backwards compatible. What I meant was simply that given that this will override all other logic (since annotation is checked for explicit mode), it needs to take care not to override actual annotations.

So, from perspective of core, returning non-null value here is equivalent to having actual annotation in creator (constructor or factory method). Having multiple constructors with `@JsonCreator` annotation would lead to exception unless there is a way to detemine one has priority over the other.

However: it may be that returning non-null JsonCreator.mode is not problematic, as that should only be called once constructor is determined to be a candidate, based on other information.
That is why I am asking as I don't actually know for sure. Modifying the test to add, say, another constructor with more arguments, would help determine that. Having multiple constructors is a common use case; sometimes with multiple public constructors.

**Comment by lpandzic** [comment]
I've tested it with a second constructor and tests still pass.
I've changed default creator binding value to null.

**Comment by cowtowncoder** [comment]
Sounds good, merged.

**Pull request merged**
